server {
    listen 80 default;
    #listen 443 default;

    server_name mtg-test.cc

    client_max_body_size 108M;

    access_log /var/log/nginx/application.access.log;
    error_log /var/log/nginx/error.log;
    #error_log "/var/log/nginx/error.log" debug;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri /index.php?$args;
    }

    if (!-e $request_filename) {
        rewrite ^.*$ /index.php last;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
    }

#    location /app {
#            proxy_http_version 1.1;
#            proxy_set_header Host $http_host;
#            proxy_set_header Scheme $scheme;
#            proxy_set_header SERVER_PORT $server_port;
#            proxy_set_header REMOTE_ADDR $remote_addr;
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header Upgrade $http_upgrade;
#            proxy_set_header Connection "Upgrade";
#
#            proxy_pass http://0.0.0.0:8080;
#    }


}
